EasyBuyService:
  InstanceName:
    settings-key: EasyBuyService-InstanceName

  ClientId:
    settings-key: EasyBuyService-ClientId

  DefaultMarkup:
    settings-key: EasyBuyService-DefaultMarkup

  TimerPeriod:
    settings-key: EasyBuyService-TimerPeriod

  DefaultPriceLifetime:
    settings-key: EasyBuyService-DefaultPriceLifetime

  Db:
    DataConnectionString:
      settings-key: EasyBuyService-DataConnectionString
      types:
        - AzureTableStorage

    LogsConnString:
      settings-key: EasyBuyService-LogsConnectionString
      types:
        - AzureTableStorage

  OrderBookSources:
    settings-key: EasyBuyService-OrderBookSources
      types:
        - JsonArray

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName

AssetsServiceClient:
  ServiceUrl:
    settings-key: AssetsServiceUrl

BalancesServiceClient:
  ServiceUrl:
    settings-key: BalancesServiceUrl

ExchangeOperationsServiceClient:
  ServiceUrl:
    settings-key: ExchangeOperationsServiceUrl

ClientAccountServiceClient:
  ServiceUrl:
    settings-key: ClientAccountServiceUrl

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl