EasyBuyService:
  InstanceName:
    settings-key: EasyBuyService-InstanceName

  WalletId:
    settings-key: EasyBuyService-WalletId
  
  Db:
    DataConnectionString:
      settings-key: EasyBuyService-DataConnectionString
      types:
        - AzureTableStorage

    LogsConnectionString:
      settings-key: EasyBuyService-LogsConnectionString
      types:
        - AzureTableStorage

  PricesPublish:
    ConnectionString:
      settings-key: RawPriceRabbitMq
      types:
        - RabbitMq
    ExchangeName:
      settings-key: EasyBuyService-PricesPublishExchangeName
  
  OrderBookSource:
    ConnectionString:
      settings-key: EasyBuyService-OrderBookSourceConnectionString
      types:
        - RabbitMq
    QueueSuffix:
      settings-key: EasyBuyService-OrderBookSourceQueueSuffix
    Exchanges:
      settings-key: EasyBuyService-OrderBookSourceExchanges
      types:
        - JsonArray

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName

AssetsServiceClient:
  ServiceUrl:
    settings-key: AssetsServiceUrl

BalancesServiceClient:
  ServiceUrl:
    settings-key: BalancesServiceUrl

ExchangeOperationsServiceClient:
  ServiceUrl:
    settings-key: ExchangeOperationsServiceUrl

ClientAccountServiceClient:
  ServiceUrl:
    settings-key: ClientAccountServiceUrl

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl