EasyBuyService:
  Db:
    DataConnectionString:
      settings-key: EasyBuyService-DataConnectionString
      types:
        - AzureTableStorage

    LogsConnString:
      settings-key: EasyBuyService-LogsConnectionString
      types:
        - AzureTableStorage

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl